# Generated by Django 5.2.1 on 2025-05-19 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0003_alter_helprequest_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='helprequest',
            name='request_type',
            field=models.CharField(choices=[('week_review', 'week Review'), ('urgent_review', 'Urgent Review'), ('doubt_session', 'Doubt Session'), ('report_issue', 'Report Issue')], max_length=20),
        ),
    ]
