# Generated by Django 5.2.1 on 2025-05-19 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0004_alter_helprequest_request_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='helprequest',
            name='request_type',
            field=models.CharField(choices=[('urgent_review', 'Urgent Review'), ('doubt_session', 'Doubt Session'), ('report_issue', 'Report Issue'), ('week_review', 'week Review')], max_length=20),
        ),
    ]
